# -*- coding: utf-8 -*-
"""calcfinc.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M5voJyZ992ig1qYn6VUJK5Jqt2791zd1
"""

# import da biblioteca

from math import log

#Inicio, mensagem ao iniciar a programação

print("Bem-vindo à calculadora de Juros Compostos!")

#Calculo do valor final
def calculo_vf():
  while True:
   print("\nPara realizar o calculo do Valor Final será necessário inserir algumas informações, insira apenas valores numericos: ")
   ci=float(input("Capital inicial (R$):") )
   i=(float(input("Taxa de juros (considerar 1 para 1%):"))/100)
   t=int(input("Periodo(meses):"))

   #Mostra os valores inseridos
   print("\nOs valores inseridos foram:")
   print(f"Capital inicial: R${ci:,.2f}".format(ci).replace(',','*').replace('.',',').replace('*','.'))
   print(f"Taxa de juros: {i*100:.1f}%")
   print(f"Periodo: {t} meses")

   #Verificar se os valores estão corretos
   verifica_vf=input("Os valores estão corretos? (s/n) ")

   if verifica_vf.lower() == "s":
     vf=ci*(1+i)**t
     return vf

#Calculo do capital inicial
def calculo_ci():
  while True:
   print("\nPara realizar o calculo do Valor Final será necessário inserir algumas informações, insira apenas valores numericos: ")
   vf=float(input("Valor final (R$):") )
   i=(float(input("Taxa de juros (considerar 1 para 1%):"))/100)
   t=int(input("Periodo(meses):"))

   #Mostra os valores inseridos
   print("\nOs valores inseridos foram:")
   print(f"Valor Final: R${vf:,.2f}".format(vf).replace(',','*').replace('.',',').replace('*','.'))
   print(f"Taxa de juros: {i*100:.1f}%")
   print(f"Periodo: {t} meses")

   #Verificar se os valores estão corretos
   verifica_ci=input("Os valores estão corretos? (s/n) ")

   if verifica_ci.lower() == "s":
     ci = vf / (1 + i)**t
     return ci

#Calculo da taxa de juros
def calculo_i():
  while True:
   print("\nPara realizar o calculo do Valor Final será necessário inserir algumas informações, insira apenas valores numericos: ")
   ci=float(input("Capital inicial (R$):") )
   vf=float(input("Valor final (R$):") )
   t=int(input("Periodo(meses):"))

   #Mostra os valores inseridos
   print("\nOs valores inseridos foram:")
   print(f"Capital inicial: R${ci:,.2f}".format(ci).replace(',','*').replace('.',',').replace('*','.'))
   print(f"Valor Final: R${vf:,.2f}".format(vf).replace(',','*').replace('.',',').replace('*','.'))
   print(f"Periodo: {t} meses")

   #Verificar se os valores estão corretos
   verifica_i=input("Os valores estão corretos? (s/n) ")

   if verifica_i.lower() == "s":
     i=(((vf/ci)**(1/t))-1)
     return i

#Calculo do periodo
def calculo_t():
  while True:
   print("\nPara realizar o calculo do Valor Final será necessário inserir algumas informações, insira apenas valores numericos: ")
   ci=float(input("Capital inicial (R$):") )
   vf=float(input("Valor final (R$):") )
   i=(float(input("Taxa de juros (considerar 1 para 1%):"))/100)

   #Mostra os valores inseridos
   print("\nOs valores inseridos foram:")
   print(f"Capital inicial: R${ci:,.2f}".format(ci).replace(',','*').replace('.',',').replace('*','.'))
   print(f"Valor Final: R${vf:,.2f}".format(vf).replace(',','*').replace('.',',').replace('*','.'))
   print(f"Taxa de juros: {i*100:.1f}%")

   #Verificar se os valores estão corretos
   verifica_t=input("Os valores estão corretos? (s/n) ")

   if verifica_t.lower() == "s":
     t = log(vf / ci) / log(1 + i)
     return t


while True:
  #Selecionar a operação desejada
  menu = input ("\nO que você gostaria de calcular?"+"\nvf = Valor Final"+"\nci = Capital Inicial"+"\nt = Período"+"\ni = Taxa de juros"+"\nResposta (sigla):")

  #Opções do menu
  if menu == "vf":
    vf=calculo_vf()
    print(f"\nO Valor Final é de: R${vf:,.2f}".format(vf).replace(',','*').replace('.',',').replace('*','.'))
  elif menu =="ci":
    ci=calculo_ci()
    print(f"\nO Valor do Capital Inicial é de: R${ci:,.2f}".format(ci).replace(',','*').replace('.',',').replace('*','.'))
  elif menu == "i":
    i=calculo_i()
    print(f"\nO Valor da taxa de juros é de:{i*100:.2f}%")
  elif menu == "t":
    t=calculo_t()
    print(f"\nO Valor do Periodo é de: {int(t)} meses")
  else:
    print("\nOpção invalida. Insira uma opção válida.")
    continue

  #verificar se terá novos calculos
  novo_calculo=input("\nDeseja realizar um novo calculo? (s/n) ")

  if novo_calculo.lower() == "n":
    print("\nSe precisar fazer mais cálculos, volte a me executar.")
    break